# ----------------------- #
#     Site Variables      #
# ----------------------- #

name: Daniel C. Dillon (dcdillon)
author: Daniel C. Dillon (dcdillon)
url: 'http://dcdillon.github.io/cpuaff'

copyright_message: '&copy; 2015 Daniel C. Dillon'
title: "cpuaff"
subtitle: "Multi-platform C++ interface to CPU affinity management"

github_url: https://github.com/dcdillon/cpuaff
github_username: dcdillon

#github_license:
#github_license_url:


# ----------------------- #
#       Site Paths        #
# ----------------------- #

# LOCAL
stylesheets: /assets/stylesheets
javascripts: /assets/javascripts
images:      /assets/images
fonts:       /assets/fonts

# GLOBAL
global_stylesheets: /cpuaff/assets/stylesheets
global_javascripts: /cpuaff/assets/javascripts
global_images:      /cpuaff/assets/images
global_fonts:       /cpuaff/assets/fonts

# ----------------------- #
#     Plugin Configs      #
# ----------------------- #

#google_analytics_id: 
#google_analytics_name: 

source_title_prefix: "GitHub: dcdillon/cpuaff"
source_url: 'https://github.com/dcdillon/cpuaff'

# ----------------------- #
#     Jekyll Configs      #
# ----------------------- #

#source: source
destination: _public
plugins: 	 _plugins

exclude: [LICENSE.md]

relative_permalinks: false
markdown: redcarpet
pygments: true

