# ----------------------- #
#     Site Variables      #
# ----------------------- #

name: Daniel C. Dillon (dcdillon)
author: Daniel C. Dillon (dcdillon)
url: 'http://github.com/dcdillon'

title: "cpuaff"
subtitle: "Multi-platform C++ interface to CPU affinity management"

github_url: https://github.com/dcdillon/cpuaff
github_username: dcdillon

github_license: The MIT License
github_license_url: https://github.com/IQAndreas/markdown-licenses/blob/master/mit.md


# ----------------------- #
#       Site Paths        #
# ----------------------- #

# LOCAL
stylesheets: /assets/stylesheets
javascripts: /assets/javascripts
images:      /assets/images
fonts:       /assets/fonts

# GLOBAL
#global_stylesheets: http://static.iqandreas.com/assets/stylesheets
#global_javascripts: http://static.iqandreas.com/assets/javascripts
#global_images:      http://static.iqandreas.com/assets/images
#global_fonts:       http://static.iqandreas.com/assets/fonts

# ----------------------- #
#     Plugin Configs      #
# ----------------------- #

google_analytics_id:   UA-44446017-1
google_analytics_name: iqandreas.com

source_title_prefix: "GitHub: dcdillon/cpuaff"
source_url: 'https://github.com/dcdillon/cpuaff'

# ----------------------- #
#     Jekyll Configs      #
# ----------------------- #

#source: source
destination: _public
plugins: 	 _plugins

exclude: [LICENSE.md]

relative_permalinks: false
markdown: redcarpet
pygments: true

